version: "3"
services:
  php_sqli:
    build: .
    ports:
    - "8000:80"
    volumes:
    - ./SQLi:/var/www/html
    links:
    - db
  php_lfi:
    build: .
    ports:
    - "8001:80"
    volumes:
    - ./LFI/site:/var/www/html
  php_xss:
      build: .
      ports:
      - "8002:80"
      volumes:
      - ./XSS:/var/www/html
  db:
    image: mysql:5.7
    volumes:
    - /var/lib/mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_HOST=%
    - MYSQL_USER=silent
    - MYSQL_PASSWORD=123456
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_DATABASE=silent